# Generated by Django 3.2.7 on 2022-04-13 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre del Equipo')),
                ('ligasGanadas', models.IntegerField()),
                ('championsGanadas', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'db_table': 'Equipo',
            },
        ),
        migrations.CreateModel(
            name='Liga',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Codigo')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripcion')),
                ('pais', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pais')),
            ],
            options={
                'verbose_name': 'Liga',
                'verbose_name_plural': 'Ligas',
                'db_table': 'Liga',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre del jugador')),
                ('apellidos', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellidos del jugador')),
                ('posicion', models.CharField(blank=True, choices=[('', '-------'), ('POR', 'Portero'), ('DEF', 'Defensa'), ('LI', 'Lateral Izquierdo'), ('LD', 'Lateral Derecho'), ('MC', 'Medio Campo'), ('EXI', 'Extremo Izquierdo'), ('EXD', 'Extremo Derecho'), ('DEL', 'Delantero')], max_length=100, null=True, verbose_name='Posicion del jugador')),
                ('goles', models.IntegerField()),
                ('asistencias', models.IntegerField()),
                ('tieneBalonDeOro', models.BooleanField(default=False)),
                ('estaLesionado', models.BooleanField(default=False)),
                ('esActivo', models.BooleanField(default=True)),
                ('fk_equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uefa.equipo', verbose_name='Equipo del jugador')),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
                'db_table': 'Jugador',
            },
        ),
        migrations.AddField(
            model_name='equipo',
            name='fk_liga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uefa.liga', verbose_name='Liga'),
        ),
    ]
