# Generated by Django 3.2.7 on 2022-04-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uefa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='esActivo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jugador',
            name='dorsal',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Dorsal del jugador'),
        ),
        migrations.AddField(
            model_name='jugador',
            name='nivel',
            field=models.PositiveIntegerField(default=0, verbose_name='Nivel del jugador'),
        ),
        migrations.AddField(
            model_name='liga',
            name='esActivo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='championsGanadas',
            field=models.IntegerField(default=0, verbose_name='Champions Ganadas'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='ligasGanadas',
            field=models.IntegerField(default=0, verbose_name='Ligas Ganadas'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='apellidos',
            field=models.CharField(max_length=100, verbose_name='Apellidos del jugador'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='asistencias',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad de asistencias'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='goles',
            field=models.PositiveIntegerField(default=0, verbose_name='Goles anotados'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre del jugador'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='posicion',
            field=models.CharField(choices=[('', '-------'), ('POR', 'Portero'), ('DEF', 'Defensa'), ('LI', 'Lateral Izquierdo'), ('LD', 'Lateral Derecho'), ('MC', 'Medio Campo'), ('EXI', 'Extremo Izquierdo'), ('EXD', 'Extremo Derecho'), ('DEL', 'Delantero')], max_length=100, verbose_name='Posicion del jugador'),
        ),
        migrations.AlterField(
            model_name='liga',
            name='descripcion',
            field=models.CharField(max_length=200, verbose_name='Descripcion'),
        ),
    ]
