# Generated by Django 3.2.7 on 2022-04-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uefa', '0003_auto_20220418_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='dorsal',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Dorsal del jugador'),
        ),
    ]
