# Generated by Django 3.2.7 on 2022-04-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uefa', '0004_alter_jugador_dorsal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='estaLesionado',
        ),
        migrations.AddField(
            model_name='jugador',
            name='esTitular',
            field=models.BooleanField(default=True),
        ),
    ]
